name = "Jayka Theme"
license = "MIT"
licenselink = ""
description = "A custom dark theme for Jayka Studios gaming website"
homepage = "https://jaykastudios.com"
tags = ["gaming", "dark", "modern"]
features = ["carousel", "animations", "responsive"]
min_version = "0.41.0"

[author]
  name = "Jayka Studios"
  homepage = "https://jaykastudios.com"
